namespace ClipboardManager
{
    [default_interface]
    runtimeclass ClipboardActionView : Microsoft.UI.Xaml.Controls.UserControl
    {
        ClipboardActionView();
        ClipboardActionView(String text);

        String Text;
        Windows.Foundation.DateTime Timestamp;

        event Windows.Foundation.TypedEventHandler<ClipboardActionView, IInspectable> Removed;

        void AddAction( String label, String format, String regex, Boolean enabled, Boolean useRegexMatchResults, Boolean ignoreCase);
        void EditAction(UInt32 pos, 
                        String format, String label, String regex, Boolean enabled, Boolean useRegexMatchResults, Boolean ignoreCase);
        Boolean IndexOf(out UInt32 pos, String label);
        Windows.Foundation.Collections.IVector<String> GetTriggersText();

        Windows.Foundation.IAsyncAction StartTour();
    }
}
