namespace ClipboardManager
{
    [default_interface]
    runtimeclass ClipboardTriggerEditControl : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClipboardTriggerEditControl();

        String TriggerLabel;
        String TriggerFormat;
        String TriggerRegex;
        Boolean IgnoreCase;
        Boolean UseSearch;
        Boolean UseRegexMatchResults;

        Windows.Foundation.IAsyncOperation<Boolean> Edit();
    }
}
