namespace ClipboardManager
{
    [default_interface]
    runtimeclass ClipboardActionView : Microsoft.UI.Xaml.Controls.UserControl
    {
        ClipboardActionView();
        ClipboardActionView(String text);

        String Text;

        event Windows.Foundation.TypedEventHandler<ClipboardActionView, IInspectable> Removed;

        void AddAction(String format, String label, String regex, Boolean enabled);
        void AddActions(IInspectable actions);
        void EditAction(UInt32 pos, String format, String label, String regex, Boolean enabled, Boolean useRegexMatchResults);
        Boolean IndexOf(out UInt32 pos, String label);

        Windows.Foundation.IAsyncAction StartTour();
    }
}
