namespace ClipboardManager
{
    [default_interface]
    runtimeclass ClipboardActionEditor : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ClipboardActionEditor();
        String ActionLabel;
        String ActionFormat;
        String ActionRegex;
        Boolean ActionEnabled;

        event Windows.Foundation.TypedEventHandler<ClipboardActionEditor, Boolean> IsOn;
        event Windows.Foundation.TypedEventHandler<ClipboardActionEditor, String> LabelChanged;
        event Windows.Foundation.TypedEventHandler<ClipboardActionEditor, String> FormatChanged;
        event Windows.Foundation.TypedEventHandler<ClipboardActionEditor, IInspectable> Removed;

        Windows.Foundation.IAsyncAction StartTour();
    }
}
