namespace ClipboardManager
{
    [default_interface]
    runtimeclass HostControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        HostControl();
        IInspectable Header;
        IInspectable HostContent;
    }
}
