import "ClipboardActionView.idl";

namespace ClipboardManager
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        MainPage(Microsoft.UI.Windowing.AppWindow appWindow);

        IObservableVector<ClipboardActionView> Actions;

        void AppClosing();
        void UpdateTitleBar();
    }
}
