import "ClipboardActionView.idl";
import "ClipboardActionEditor.idl";

namespace ClipboardManager
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        MainPage(Microsoft.UI.Windowing.AppWindow appWindow);

        IObservableVector<ClipboardActionView> Actions;
        IObservableVector<ClipboardActionEditor> ClipboardTriggers;
        Boolean OverlayEnabled;

        void AppClosing();
        void UpdateTitleBar();
        void UpdateUserFile(String pathString);
        void ReceiveWindowMessage(UInt64 message, UInt64 param);
    }
}
